services:
  web:
    build: .
    container_name: reservation_api_web
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
    volumes:
      - .:/app
      - media_volume:/app/media

  db:
    image: postgres:16
    container_name: reservation_api_db
    environment:
      POSTGRES_DB: reservation_api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media_volume: